### ISSUE TITLE
DB problem bei swiping

### ISSUE THREAD

**Issue by JonasMa** [IrisF/FingerDingApp#24]
06-07 13:18:57.512 4187-4187/ifi.lmu.com.handmeasurementstudy E/SQLiteDatabase: Error inserting ...
                                                                                android.database.sqlite.SQLiteException: **table swiping has no column named swipeId** (code 1): , while compiling: INSERT INTO swiping(rotY,graY,userID,y,orientationX,time,graX,accZ,x,accY,swipeId,gyrY,rotZ,orientationZ,accX,orientationY,gyrX,gyrZ,rotX,graZ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                                                                                    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:917)
                                                                                    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:528)
                                                                                    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                    at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1547)
                                                                                    at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1404)
                                                                                    at ifi.lmu.com.handmeasurementstudy.db.**DBHandler.insertSwipe(DBHandler.java:499)**
                                                                                    at ifi.lmu.com.handmeasurementstudy.system.ActivityManager.StoreResultsInDatabase(ActivityManager.java:219)
                                                                                    at ifi.lmu.com.handmeasurementstudy.system.ActivityManager.onActivityResult(ActivityManager.java:264)

**Comment by JonasMa** [comment]
hab nachgeschaut, check das auch nicht, sollte eigentlich da sein...
